name: Release Helm Chart

on:                                                                                                           
  push:                                                                                                       
    branches:                                                                                                 
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup golang for helmify
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Configure Git
        run: |
          apt update && apt install git -y
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: imranismail/setup-kustomize@v2
      - run: |
          go install github.com/arttor/helmify@latest/cmd/helmify
          kustomize edit set image  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          kustomize build config/default | helmify cosmos-operator && mv cosmos-operator -R ./charts/
          git add ./charts/
          git commit -m 'AUTOGENERATED: Update helm chart with latest kustomize output'
          git push
 
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
