name: Release Helm Chart

on:
  pull_request:
    types:
      - closed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup golang for helmify
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Configure Git
        run: |
          apt update && apt install git -y
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: imranismail/setup-kustomize@v2
      - run: |
          go install github.com/arttor/helmify/cmd/helmify@latest
          cd config/manager && kustomize edit set image controller=ghcr.io/strangelove-ventures/cosmos-operator:latest
          cd ../../ && kustomize build config/default | helmify cosmos-operator && rm -rf ./charts/cosmos-operator && mv cosmos-operator ./charts/
          git add ./charts/
          git commit -m 'AUTOGENERATED: Update helm chart with latest kustomize output'
          git push
 
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
